// backend/src/media/media.service.ts
import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common'; import {PrismaService} from '../prisma/prisma.service'; import type {MediaStatus} from './media.types';
const allowed:Record<string,string[]>={DRAFT:['PENDING'],PENDING:['IN_REVIEW'],IN_REVIEW:['PENDING','ACADEMIC_REVIEW','REVISION','REJECTED'],REVISION:['PENDING'],ACADEMIC_REVIEW:['APPROVED','ACADEMIC_REVISION'],ACADEMIC_REVISION:['ACADEMIC_REVIEW'],APPROVED:['ARCHIVED'],REJECTED:[],ARCHIVED:[]};
@Injectable() export class MediaService{constructor(private p:PrismaService){}
 include={owner:{select:{id:true,name:true,email:true,department:true}},assignee:{select:{id:true,name:true}},files:true,reviews:{include:{reviewer:{select:{name:true,role:true}},items:true},orderBy:{createdAt:'desc' as const}},statusLogs:{orderBy:{createdAt:'desc' as const}}};
 code(){return `MED-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${Math.floor(100+Math.random()*900)}`}
 async create(user:any,d:any,files:any[]=[]){if(user.role!=='TEACHER')throw new ForbiddenException(); const status=d.submit?'PENDING':'DRAFT'; return this.p.media.create({data:{code:this.code(),title:d.title,description:d.description??'',subject:d.subject,subjectGroup:d.subjectGroup??d.subject,gradeLevel:d.gradeLevel,mediaType:d.mediaType??'เอกสาร',learningObjectives:d.learningObjectives??{},assessments:d.assessments??{},learningProcess:d.learningProcess,license:d.license,tags:d.tags??[],attachmentNote:d.attachmentNote,status,reviewStage:status==='PENDING'?'SUBJECT_GROUP':null,ownerId:user.sub,files:{create:files.map(f=>({name:f.originalname,mimeType:f.mimetype,size:f.size,path:f.path}))}},include:this.include})}
 async mine(id:string){return this.p.media.findMany({where:{ownerId:id},include:this.include,orderBy:{updatedAt:'desc'}})}
 async publicList(){return this.p.media.findMany({where:{status:'APPROVED'},include:this.include,orderBy:{updatedAt:'desc'}})}
 async one(id:string,user:any){const m=await this.p.media.findUnique({where:{id},include:this.include});if(!m)throw new NotFoundException(); if(m.status!=='APPROVED'&&m.ownerId!==user.sub&&user.role==='TEACHER')throw new NotFoundException();return m}
 async queue(user:any){const where=user.role==='ADMIN'?{status:{in:['ACADEMIC_REVIEW','ACADEMIC_REVISION'] as MediaStatus[]}}:user.role==='REVIEWER'?{subjectGroup:user.department,status:{in:['PENDING','IN_REVIEW','REVISION'] as MediaStatus[]}}:{id:'__none__'};return this.p.media.findMany({where,include:this.include,orderBy:{updatedAt:'asc'}})}
 async transition(id:string,user:any,to:MediaStatus,reason?:string){return this.p.$transaction(async (tx:any)=>{const m=await tx.media.findUnique({where:{id},include:{files:true,reviews:{include:{items:true}}}});if(!m)throw new NotFoundException(); if(!allowed[m.status]?.includes(to))throw new BadRequestException('สถานะนี้เปลี่ยนไปปลายทางที่ขอไม่ได้');
 if(m.status==='DRAFT'&&to==='PENDING'&&m.ownerId!==user.sub)throw new ForbiddenException(); if(m.status==='PENDING'&&to==='IN_REVIEW'&&user.role!=='REVIEWER')throw new ForbiddenException(); if(m.status==='IN_REVIEW'&&m.assigneeId&&m.assigneeId!==user.sub)throw new ForbiddenException(); if(['APPROVED','ACADEMIC_REVISION'].includes(to)&&user.role!=='ADMIN')throw new ForbiddenException();
 if(['REVISION','REJECTED'].includes(to)&&user.role!=='REVIEWER')throw new ForbiddenException(); if(to==='REJECTED'&&!reason?.trim())throw new BadRequestException('ต้องระบุเหตุผล'); if(to==='PENDING'&&m.files.length<1)throw new BadRequestException('ต้องมีไฟล์อย่างน้อย 1 ไฟล์');
 let version=m.version; if((m.status==='REVISION'&&to==='PENDING')||(m.status==='ACADEMIC_REVISION'&&to==='ACADEMIC_REVIEW')){await tx.mediaVersion.create({data:{mediaId:m.id,version:m.version,snapshot:m as any}});version++}
 const assigneeId=to==='IN_REVIEW'?user.sub:to==='PENDING'?null:m.assigneeId; const reviewStage=['ACADEMIC_REVIEW','ACADEMIC_REVISION','APPROVED'].includes(to)?'ACADEMIC':to==='PENDING'||to==='IN_REVIEW'||to==='REVISION'?'SUBJECT_GROUP':m.reviewStage;
 await tx.statusLog.create({data:{mediaId:id,actorId:user.sub,fromStatus:m.status,toStatus:to,reason}}); const updated=await tx.media.update({where:{id},data:{status:to,assigneeId,reviewStage:reviewStage as any,version},include:this.include}); if(['REVISION','REJECTED','APPROVED','ACADEMIC_REVISION'].includes(to)){await tx.notification.create({data:{userId:m.ownerId,title:`อัปเดตสถานะ ${m.code}`,message:`${m.title} → ${to}`,href:`/my-media/${m.id}`}})} return updated;})}
 async remove(id:string,user:any){const m=await this.p.media.findUnique({where:{id}});if(!m)throw new NotFoundException();if(m.ownerId!==user.sub||m.status!=='DRAFT')throw new ForbiddenException();await this.p.media.delete({where:{id}});return{ok:true}}
}
