-- supabase/migrations/202608070001_enterprise_media_qa.sql
create extension if not exists pgcrypto;
create type public.user_role as enum ('TEACHER','REVIEWER','ADMIN');
create type public.media_status as enum ('DRAFT','PENDING','IN_REVIEW','REVISION','APPROVED','REJECTED','ARCHIVED');

create table public.departments(id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', role public.user_role not null default 'TEACHER', department_id uuid references public.departments(id), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.media(id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id), title text not null, description text not null default '', subject text not null default '', grade text not null default '', media_type text not null default '', learning_objectives text not null default '', license text, status public.media_status not null default 'DRAFT', current_version int not null default 1, published_at timestamptz, archived_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.media_versions(id uuid primary key default gen_random_uuid(), media_id uuid not null references public.media(id) on delete cascade, version_no int not null, submitted_by uuid not null references public.profiles(id), change_note text, metadata_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(media_id,version_no));
create table public.media_files(id uuid primary key default gen_random_uuid(), version_id uuid not null references public.media_versions(id) on delete cascade, bucket text not null default 'media-files', storage_path text not null unique, original_name text not null, mime_type text not null, size_bytes bigint not null check(size_bytes>0), sha256 text, created_at timestamptz not null default now());
create table public.review_assignments(id uuid primary key default gen_random_uuid(), media_id uuid not null references public.media(id), version_id uuid not null references public.media_versions(id), reviewer_id uuid not null references public.profiles(id), assigned_by uuid references public.profiles(id), accepted_at timestamptz, released_at timestamptz, created_at timestamptz not null default now());
create unique index one_active_assignment_per_media on public.review_assignments(media_id) where released_at is null;
create table public.reviews(id uuid primary key default gen_random_uuid(), media_id uuid not null references public.media(id), version_id uuid not null references public.media_versions(id), reviewer_id uuid not null references public.profiles(id), decision public.media_status check(decision in ('APPROVED','REVISION','REJECTED')), topic_results jsonb not null default '{}'::jsonb, reason text, created_at timestamptz not null default now(), completed_at timestamptz);
create table public.review_comments(id uuid primary key default gen_random_uuid(), media_id uuid not null references public.media(id), version_id uuid not null references public.media_versions(id), author_id uuid not null references public.profiles(id), topic_key text, body text not null, resolved_at timestamptz, created_at timestamptz not null default now());
create table public.ai_reviews(id uuid primary key default gen_random_uuid(), media_id uuid not null references public.media(id), version_id uuid not null references public.media_versions(id), provider text not null, model text not null, summary text not null default '', findings jsonb not null default '[]'::jsonb, draft_feedback text, prompt_version text not null default 'v1', created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, kind text not null, title text not null, body text not null default '', href text, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), entity_type text not null, entity_id uuid, action text not null, from_status public.media_status, to_status public.media_status, reason text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.download_events(id bigint generated always as identity primary key, media_id uuid not null references public.media(id), user_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.favorites(user_id uuid not null references public.profiles(id) on delete cascade, media_id uuid not null references public.media(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,media_id));

-- คืน null เมื่อล็อกอินแล้วแต่ยังไม่มีแถวใน profiles ตัวเทียบทุกตัวจะได้ผลเป็น null
-- ซึ่ง policy ถือว่าไม่ผ่าน = ปฏิเสธไว้ก่อน ห้ามใส่ค่า default เป็นบทบาทใดบทบาทหนึ่ง
create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid(); $$;
create or replace function public.is_staff_reviewer() returns boolean language sql stable as $$ select public.current_role() in ('REVIEWER','ADMIN'); $$;

alter table public.profiles enable row level security;alter table public.media enable row level security;alter table public.media_versions enable row level security;alter table public.media_files enable row level security;alter table public.review_assignments enable row level security;alter table public.reviews enable row level security;alter table public.review_comments enable row level security;alter table public.ai_reviews enable row level security;alter table public.notifications enable row level security;alter table public.audit_logs enable row level security;alter table public.download_events enable row level security;alter table public.favorites enable row level security;

create policy profiles_self_or_admin on public.profiles for select to authenticated using(id=auth.uid() or public.current_role()='ADMIN');
create policy media_read on public.media for select using(status='APPROVED' or owner_id=auth.uid() or public.is_staff_reviewer());
create policy media_owner_insert on public.media for insert to authenticated with check(owner_id=auth.uid());
create policy media_owner_update_draft_revision on public.media for update to authenticated using(owner_id=auth.uid() and status in ('DRAFT','REVISION')) with check(owner_id=auth.uid());
create policy version_read on public.media_versions for select using(exists(select 1 from public.media m where m.id=media_id and (m.status='APPROVED' or m.owner_id=auth.uid() or public.is_staff_reviewer())));
create policy review_staff on public.reviews for all to authenticated using(public.is_staff_reviewer()) with check(public.is_staff_reviewer());
create policy assignments_staff on public.review_assignments for all to authenticated using(public.is_staff_reviewer()) with check(public.is_staff_reviewer());
create policy comments_visible on public.review_comments for select to authenticated using(author_id=auth.uid() or public.is_staff_reviewer() or exists(select 1 from public.media m where m.id=media_id and m.owner_id=auth.uid()));
create policy comments_insert on public.review_comments for insert to authenticated with check(author_id=auth.uid());
create policy ai_staff_read on public.ai_reviews for select to authenticated using(public.is_staff_reviewer() or exists(select 1 from public.media m where m.id=media_id and m.owner_id=auth.uid()));
create policy notifications_self on public.notifications for select to authenticated using(user_id=auth.uid());
create policy audit_admin_reviewer on public.audit_logs for select to authenticated using(public.is_staff_reviewer());
create policy favorite_self on public.favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy download_approved on public.download_events for insert to authenticated with check(exists(select 1 from public.media m where m.id=media_id and m.status='APPROVED'));
